from src.brain.agents.planner import create_plan, AgentState
from src.governance.guardian import GraniteGuardian
from src.brain.rag_engine import query_knowledge_base
from src.system.tools.civil_engineer import IncidentReport


class CivicOrchestrator:
    """
    Central orchestrator for the CivicNerve agent pipeline.
    Coordinates: Language → Planner → Guardian → RAG → Response
    """

    def __init__(self):
        self.guardian = GraniteGuardian()

    def run(self, user_input: str, image_desc: str = "None", lang: str = "en") -> dict:
        """
        Runs the full agentic pipeline for a citizen report.
        Returns a structured result with work order, audit trail, and bylaw context.
        """
        # Step 1: Build initial state
        state = AgentState(
            messages=[("user", user_input)],
            incident_report=IncidentReport(
                summary="Pending", location="Unknown", detected_hazards=[]
            ),
            blueprint_data="Pending",
            final_work_order=None,
            guardian_review="Pending"
        )

        # Step 2: Run planner (classify + generate work order)
        try:
            plan_result = create_plan(state)
        except Exception as e:
            return {
                "work_order": None,
                "guardian_review": "ERROR",
                "audit_trail": {"status": "ERROR", "reason": str(e)},
                "relevant_bylaws": [],
                "detected_lang": lang
            }

        # Step 3: Enrich with bylaw context from RAG
        try:
            bylaws = query_knowledge_base(user_input)
        except Exception:
            bylaws = []

        # Step 4: Guardian safety + budget audit
        work_order = plan_result.get("final_work_order")
        if work_order:
            audit_log = self.guardian.audit_plan(work_order)
        else:
            audit_log = {"status": "ERROR", "reason": "No plan generated by planner."}

        return {
            "work_order": work_order,
            "guardian_review": audit_log.get("status", "ERROR"),
            "audit_trail": audit_log,
            "relevant_bylaws": bylaws,
            "detected_lang": lang
        }
